#! /bin/sh


# dependency: wget

# this script downloads debian packages from various official repos
# and ppas for installation on ubuntu 16.04

wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/b/bash-completion/bash-completion_2.1-4.2ubuntu1.1_all.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu/pool/main/c/carla-bridge-windows/carla-bridge-win32_1.9.5~git20160801_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu/pool/main/c/carla-git/carla-git_1.9.5~git20160801_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/c/cmake/cmake_3.5.1-1ubuntu2_amd64.deb
wget -c http://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_53.0.2785.101-1_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu/pool/main/j/jackass/jackass_20140520-1kxstudio1_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/ubuntus/ubuntu/pool/main/k/kxstudio-repos/kxstudio-repos_9.3.0~xenial1_all.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/ubuntus/ubuntu/pool/main/k/kxstudio-repos/kxstudio-repos-gcc5_9.3.0~xenial1_all.deb
wget -c http://liveusb.info/multisystem/depot/dists/all/main/binary-amd64/m/multisystem_1.0361_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/o/openjdk-8/openjdk-8-jre-headless_8u91-b14-3ubuntu1~16.04.1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/multiverse/p/pepperflashplugin-nonfree/pepperflashplugin-nonfree_1.8.2ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/v/vlc/vlc_2.2.2-5_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/v/vlc/vlc-plugin-jack_2.2.2-5_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/b/bzip2/bzip2_1.0.6-8_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/n/newt/whiptail_0.52.18-1ubuntu2_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/a/acetoneiso/acetoneiso_2.4-2_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/a/ark/ark_15.12.3-0ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/a/audacity/audacity_2.1.2-1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/a/audacity/audacity-data_2.1.2-1_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/b/basket/basket_2.10~beta+git20150905.faa6dce-1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/b/build-essential/build-essential_12.1ubuntu2_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu/pool/main/c/cadence/cadence_0.8.1+git20151026_all.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu/pool/main/c/carla-git/carla-bridge-linux32_1.9.5~git20160801_i386.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu/pool/main/c/carla-bridge-wine/carla-bridge-wine32_1.9.5+git20160114.2_i386.deb
wget -c http://kxstudio.linuxaudio.org/repo/pool/free/carla-bridge-wine64_1.9.5+git20160114_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/c/checkinstall/checkinstall_1.6.2-4ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/g/gcc-5/cpp-5_5.4.0-6ubuntu1~16.04.2_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/c/cpufrequtils/cpufrequtils_008-1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/d/devscripts/devscripts_2.16.2ubuntu3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/d/dialog/dialog_1.3-20160209-1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/d/dolphin/dolphin_15.12.3-0ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/s/syslinux/extlinux_6.03+dfsg-11ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/e/extra-cmake-modules/extra-cmake-modules_5.18.0-0ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/f/fakeroot/fakeroot_1.20.2-1ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/f/fatresize/fatresize_1.0.2-9_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/f/filelight/filelight_15.12.3-0ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/f/fluidsynth/fluidsynth_1.1.6-3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/g/gparted/gparted_0.25.0-1_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/gcc5/ubuntu/pool/main/h/hydrogen/hydrogen_0.9.6.1-1kxstudio2v5_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/music/ubuntu/pool/main/h/hydrogen-drumkits/hydrogen-drumkits-effects_2016.08.01-1kxstudio1_all.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/music/ubuntu/pool/main/h/hydrogen-drumkits/hydrogen-drumkits_2016.08.01-1kxstudio1_all.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu/pool/main/j/jack-keyboard/jack-keyboard_2.7.1-1kxstudio1.1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/j/jack-mixer/jack-mixer_10-1build1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/j/jackd-defaults/jackd_5_all.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/ubuntus/ubuntu/pool/main/j/jackd2/jackd2_1.9.11~20160620-5~xenial1_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/ubuntus/ubuntu/pool/main/j/jackd2/jackd2-firewire_1.9.11~20160620-5~xenial1_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/gcc5/ubuntu/pool/main/j/jalv/jalv_1.4.7+svn5733-1kxstudio2v5_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/j/jamin/jamin_0.97.14~cvs~81203-4build1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/kate4/kate-data_4.14.3-0ubuntu4_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/kate4/katepart_4.14.3-0ubuntu4_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/kate/kate_15.12.3-0ubuntu2_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/kde-baseapps/kde-baseapps-bin_15.12.3-0ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/kdesudo/kdesudo_3.4.2.4+repack-2ubuntu4_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/kio/kio_5.18.0-0ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/kmix/kmix_15.12.3-0ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/konsole4/konsole4-kpart_4.14.3-0ubuntu3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/konsole/konsole_15.12.3-0ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/konsole/konsole-kpart_15.12.3-0ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/krename/krename_4.0.9-3build3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/ktexteditor/ktexteditor-katepart_5.18.0-0ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/k/kate/kwrite_15.12.3-0ubuntu2_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu/pool/main/k/kxstudio-meta/kxstudio-meta-audio-plugins-vst_5.9.44_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu/pool/main/k/kxstudio-meta/kxstudio-meta-restricted-extras_5.9.44_all.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/kxstudio/ubuntu/pool/main/k/kxstudio-meta/kxstudio-meta-wine_5.9.44_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/libl/liblxqt/liblxqt-data_0.10.0-1ubuntu1_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/libl/liblxqt/liblxqt0_0.10.0-1ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lximage-qt/lximage-qt_0.4.0+20160108-1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-metapackages/lxqt_4_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-about/lxqt-about_0.10.0-3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-admin/lxqt-admin_0.10.0-3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-common/lxqt-common_0.10.0-2_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-config/lxqt-config_0.10.0-3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-metapackages/lxqt-core_4_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-globalkeys/lxqt-globalkeys_0.10.0-5_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-notificationd/lxqt-notificationd_0.10.0-2_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-openssh-askpass/lxqt-openssh-askpass_0.10.0-3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-panel/lxqt-panel_0.10.0-7_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-policykit/lxqt-policykit_0.10.0-3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-powermanagement/lxqt-powermanagement_0.10.0-3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-qtplugin/lxqt-qtplugin_0.10.0-3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-runner/lxqt-runner_0.10.0-3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-session/lxqt-session_0.10.0-1ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/l/lxqt-sudo/lxqt-sudo_0.10.0-3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/m/makeself/makeself_2.2.0-1_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/m/menulibre/menulibre_2.1.3-0ubuntu1_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/n/noblenote/noblenote_1.0.8-1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/o/openjdk-8/openjdk-8-jdk_8u91-b14-3ubuntu1~16.04.1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/p/packagesearch/packagesearch_2.7.5_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/p/pkg-config/pkg-config_0.29.1-0ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/p/plank/plank_0.11.1-1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/q/q4wine/q4wine_1.2-r2-1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/libq/libqapt/qapt-utils_3.0.2-0ubuntu1.1_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/q/qbittorrent/qbittorrent_3.3.1-1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/q/qsynth/qsynth_0.4.0-1_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/apps/ubuntu/pool/main/q/qtractor/qtractor_0.7.8-1kxstudio1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/s/scons/scons_2.4.1-1_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/s/sox/sox_14.4.1-5_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/s/squashfs-tools/squashfs-tools_4.3-3ubuntu2_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/s/synaptic/synaptic_0.83_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/s/syslinux/syslinux_6.03+dfsg-11ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/s/syslinux/syslinux-utils_6.03+dfsg-11ubuntu1_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu/pool/main/d/distrho-ports/tal-plugins_20160323-1kxstudio2_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/u/unetbootin/unetbootin_608-1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/u/unzip/unzip_6.0-20ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/v/vorbis-tools/vorbis-tools_1.4.0-7ubuntu1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/y/yakuake/yakuake_2.9.9-3_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/z/zenity/zenity_3.18.1.1-1ubuntu2_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/z/zenity/zenity-common_3.18.1.1-1ubuntu2_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/main/z/zip/zip_3.0-11_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu/pool/main/z/zynaddsubfx/zynaddsubfx_2.5.4-1kxstudio1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/a/a2jmidid/a2jmidid_8~dfsg0-1ubuntu2_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/plugins/ubuntu/pool/main/c/calf-git/calf-plugins-git_0.0.60+git20160727-1kxstudio1_amd64.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/c/cmake-extras/cmake-extras_0.6+16.04.20160215-0ubuntu2_all.deb
wget -c http://us.archive.ubuntu.com/ubuntu/pool/universe/e/equivs/equivs_2.0.9+nmu1_all.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/gcc5-deps/ubuntu/pool/main/f/flac-static/flac_1.3.1-1kxstudio2v5_amd64.deb
wget -c http://liveusb.info/multisystem/depot/dists/all/main/binary-amd64/g/gtkdialog_0.8.3-2_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/gcc5/ubuntu/pool/main/j/jalv.select/jalv.select_0.2+git20151012v5_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/gcc5/ubuntu/pool/main/s/synthclone/synthclone_0.3.0+git20130916-1kxstudio2v5_amd64.deb
wget -c http://ppa.launchpad.net/kxstudio-debian/gcc5/ubuntu/pool/main/t/triceratops-lv2/triceratops-lv2_0.3.0-1kxstudio1v5_amd64.deb
